### ISSUE TITLE
Invalid Basic Auth Header

### ISSUE THREAD

**Issue by maksymkuzko** [SumoLogic-Labs/sumologic-grafana-datasource#39]
I tried to add SumoLogic as a source and used the access ID and key as the user and password. I used an access point from my account.  Access - server(not browser).
Always error `Invalid Basic Auth Header`

**Comment by akononenko-sumo** [comment]
Hi @maksymkuzko ! Can you please provide what URL was used for the API?

**Comment by maksymkuzko** [comment]
https://api.us2.sumologic.com/api/

**Comment by akononenko-sumo** [comment]
@maksymkuzko maybe you would be able to paste whole response from the browser network tab for this?

**Comment by cg-nz** [comment]
Same with us unfortunately. Brand new access key

Browser network tab response
`{"message":"Invalid Basic Auth Header","traceID":""}`

https://api.au.sumologic.com/api/

**Comment by akononenko-sumo** [comment]
@cg-nz can you please paste a screenshot with your plugin configuration? (please ensure that API key details are blurred)

**Comment by cg-nz** [comment]
No problem. Thank you

![CleanShot 2023-08-01 at 09 13 17](https://github.com/SumoLogic-Labs/sumologic-grafana-datasource/assets/1491251/3db760ec-c52c-4347-b453-b23b7cd12e7f)

**Comment by cg-nz** [comment]
Hi. Thanks. Sorry for the delay.

Unfortunately the same error.

```
response:Object
message:"Invalid Basic Auth Header"
traceID:""
```

There's not really anything coming out of the plugin/grafana logs aside the above, even changing root Grafana log level.
I haven't got to the point of trying to fire up the full plugin debugging setup that a normal plugin developer would use, but I can try if I have some time this weekend.

Thanks.

**Comment by akononenko-sumo** [comment]
@cg-nz can you please test with `Access: Browser` (just ensure that you've enabled CORS in Sumo Admin Panel for used Access Key) and also please test without leading slash in API URL, so instead of `https://api.au.sumologic.com/api/` please try this one `https://api.au.sumologic.com/api`

**Comment by cg-nz** [comment]
Hi

Thanks, using `Access: Browser` and no trailing / , it works

![CleanShot 2023-08-07 at 09 23 56](https://github.com/SumoLogic-Labs/sumologic-grafana-datasource/assets/1491251/2571a76f-aff3-462b-8fc1-5fa81b63d7ee)

Using `Access: Browser` and trailing slash it fails:
![CleanShot 2023-08-07 at 09 24 32](https://github.com/SumoLogic-Labs/sumologic-grafana-datasource/assets/1491251/fcb0f510-82e2-42a9-81d6-ec89c1f30356)


Back on `Server: (default)` with or without trailing slash fails on both as above.

Cheers

**Comment by akononenko-sumo** [comment]
Thank you @cg-nz, I will close this issue as solution has been found.
