### ISSUE TITLE
not seeing the plugin in Grafana GA version 

### ISSUE THREAD

**Issue by ashoktmw** [SumoLogic-Labs/sumologic-grafana-datasource#42]
As per the document 
The GA version of sumologic-metrics-grafana-datasource will be available on https://grafana.com/plugins. At that point, the plugin will be installable using the Grafana command-line interface.

I'm using Sumo Logic Enterprise version and Grafana Enterprise Version with v10, While im trying to use the plugin not seeing the plugin name in the Grafana plugins list. Please check on this as i see this plugin issues are fixed to use from v9 onwards. 

Thanks for your great work and well job done.

**Comment by akononenko-sumo** [comment]
Thank you @ashoktmw for the submitted issue!

We've submitted our plugin for the Grafana review, however they does not provide timeline on how long this process may take. We would share update as soon as we would have more information.

**Comment by shekatkar-chinmay** [comment]
@akononenko-sumo Hello! 
I've been facing the same issue, but could you please let me know if there's any new updates from Grafana in the matter ? 

Thanks for your great work!

**Comment by akononenko-sumo** [comment]
Unfortunately we cannot provide any timeline on Grafana Cloud. However it still possible to setup plugin in on-premise configuration

**Comment by ashoktmw** [comment]
@akononenko-sumo  - please share the steps to install them manually in grafana cloud or grafana on-premise. 
I will try with 'UNSIGNED_PLUGINS' option

**Comment by ashoktmw** [comment]
plugin displayed in grafana plugins section
